openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteoramaapi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tasteoramaapi
tags:
  - name: Auth
    description: Registration, login and logout
  - name: Categories
    description: This is operations about categories
  - name: Recipes
    description: This is operations about recipes
servers:
  - url: https://tasteoramaapi.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /api/categories:
    get:
      $ref: '../swagger/paths/categories.yaml'
  /api/ingredients:
    get:
      $ref: '../swagger/paths/ingredients.yaml'
  /api/recipes:
    get:
      $ref: '../swagger/paths/recipes/search.yaml'
    post:
      $ref: '../swagger/paths/recipes/post.yaml'
  /api/recipes/{id}:
    get:
      $ref: '../swagger/paths/recipes/{id}/get.yaml'
  /api/recipes/favorites/{id}:
    post:
      $ref: '../swagger/paths/recipes/{id}/addFavoriteRecipe.yaml'
    delete:
      $ref: '../swagger/paths/recipes/favorites/{id}/delete.yaml'
  /api/users:
    get:
      $ref: '../swagger/paths/users.yaml'
  /api/recipes/own:
    get:
      $ref: '../swagger/paths/recipes/own/get.yaml'
  /api/recipes/favorites:
    get:
      $ref: '../swagger/paths/recipes/favorites/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
