openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteoramaapi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tasteoramaapi
tags:
  - name: Categories
    description: This is operations about categories
  - name: Recipes
    description: This is operations about recipes
servers:
  - url: http://127.0.0.1:3000
  - url: https://tasteoramaapi.onrender.com
paths:
  /api/categories:
    get:
<<<<<<< Updated upstream
      $ref: '../swagger/paths/categories.yaml'
  /api/ingredients:
    get:
      $ref: '../swagger/paths/ingredients.yaml'
=======
      $ref: '../swagger/paths/categories/categories.yaml'
>>>>>>> Stashed changes
  /api/recipes:
    get:
      $ref: '../swagger/paths/recipe/recipes.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Recipe:
      $ref: '../swagger/components/schemas/Recipe.yaml'
  responses:
    RecipesList:
      $ref: '../swagger/components/responses/RecipesList.yaml'
