openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteoramaapi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tasteoramaapi
tags:
  - name: Auth
    description: Registration and login
  - name: Categories
    description: This is operations about categories
  - name: Recipes
    description: This is operations about recipes
servers:
  - url: http://127.0.0.1:3000
  - url: https://tasteoramaapi.onrender.com
paths:
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /api/categories:
    get:
      $ref: '../swagger/paths/categories.yaml'
  /api/ingredients:
    get:
      $ref: '../swagger/paths/ingredients.yaml'
  /api/recipes:
    post:
      $ref: '../swagger/paths/recipes/post.yaml'
  /api/recipes/{id}:
    get:
      $ref: '../swagger/paths/recipes/{id}/get.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
