openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteoramaapi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tasteoramaapi
servers:
  - url: http://127.0.0.1:3000
  - url: https://tasteoramaapi.onrender.com

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
