type: object
title: Recipe
description: Recipe information
required:
  - _id
  - title
  - category
  - owner
  - instructions
  - description
  - time
  - ingredients
properties:
  _id:
    type: string
    description: Unique identifier of the recipe
    example: 6462a8f74c3d0ddd28897fcd
  title:
    type: string
    description: Recipe's title
    example: Battenberg Cake
  category:
    type: string
    description: Recipe's category
    example: Dessert
  owner:
    type: string
    description: ID of the user who created the recipe
    example: 64c8d958249fae54bae90bb9
  area:
    type: string
    description: Recipe's area or origin
    example: British
  instructions:
    type: string
    description: Recipe's instructions
    example: Heat oven to 180C/160C fan/gas 4 and line the base...
  description:
    type: string
    description: Recipe's description
    example: A classic British cake made with almond sponge cake...
  thumb:
    type: string
    format: binary
    description: Recipe's photo
    example: https://ftp.goit.study/img/so-yummy/preview/Battenberg%20Cake.jpg
  time:
    type: string
    description: Recipe's cooking time in minutes
    example: '60'
  ingredients:
    type: array
    description: List of ingredients with measurements
    items:
      type: object
      required:
        - id
        - measure
      properties:
        id:
          type: string
          description: Ingredient ID
          example: 640c2dd963a319ea671e367e
        measure:
          type: string
          description: Amount of ingredient
          example: 175g
  createdAt:
    type: string
    format: date-time
    example: '2023-03-11T10:25:33.243Z'
  updatedAt:
    type: string
    format: date-time
    example: '2024-03-03T16:47:51.976Z'
